### ISSUE TITLE
audacium.seb1g.live (website) theme problems. Hard to read.

### ISSUE THREAD

**Issue by JYamihud** [SartoxSoftware/audacium#24]
# Issue

I already issued a similar bug on [Tenacity](https://github.com/tenacityteam/tenacity/issues/135), which had a white background website with a dark text. And my browser had some trouble with it. Probably since I'm using a global dark theme. 

A lot of people might use similar themes. And if the background of the page is undefined the problem is that the text is dark on dark. On Audacium site is not that big of a deal, since the text is quite grey. So It's kind of visible. Still hard to read.
![2021-07-08_16-52](https://user-images.githubusercontent.com/27649397/124933946-f8015b80-e00c-11eb-8336-71d99fe442a7.png)

# Fix

 - Add a hard coded background to the page.

**Comment by AnErrupTion** [comment]
Are you using Dark Reader? Normally the background is white, so how did you modify the page's background color?

**Comment by realseb1g** [comment]
Disable DarkReader if you have it.

**Comment by AnErrupTion** [comment]
No it works fine with Dark Reader.

**Comment by realseb1g** [comment]
Weird?

On 8 July 2021 22.01.50 EEST, ShiningLea ***@***.***> wrote:
>No it works fine with Dark Reader.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/SartoxOnlyGNU/audacium/issues/24#issuecomment-876673081

-- 
Lähetetty Android-laitteestani K-9 Maililla. Pahoittelut vähäsanaisuudestani.

**Comment by loquesangra** [comment]
Maybe use some less bloated page theme? <_<

**Comment by SFR-git** [comment]
Hey, Tenacity's website creator here. The problem was with the background being unset — it defaults to white on many (but not all) browsers. It's a couple of lines in CSS, nothing big.

**Comment by AnErrupTion** [comment]
> Maybe use some less bloated page theme? <_<

If it doesn't have JS it's not bloated :D


> Hey, Tenacity's website creator here. The problem was with the background being unset — it defaults to white on many (but not all) browsers. It's a couple of lines in CSS, nothing big.

Yeah I know, I'll fix that soon.

**Comment by loquesangra** [comment]
> If it doesn't have JS it's not bloated :D
If it looks bad on NetSurf it's bloated :D

**Comment by AnErrupTion** [comment]
No that means it doesn't render HTML/CSS correctly :D (And I've tried NetSurf I know what I'm talking about)

**Comment by AnErrupTion** [comment]
A major problem is that I'm using markdown instead of HTML so that the page renders correctly (yes, jekyll uses markdown for pages) and thus there's no CSS.

**Comment by FrostKnight** [comment]
Thank you for forking audacity, I hope you will make this fork more lightweight,privacy friendly, etc...

More on topic though, I hope this website issue will get fixed, for some people it might be annoying.

**Comment by jt15s** [comment]
@AnErrupTion Not sure if all static site generators are similar, but I've used Hugo before and there's a spot where the CSS for the site theme is stored and you can easily change that to your liking. Not sure if this will help but I did a quick search and found this page on using Jekyll with CSS: http://simpleprimate.com/jekyll-for-designers/blog/css/
