### ISSUE TITLE
Cannot import ffmpeg into audacium

### ISSUE THREAD

**Issue by mystic-akito** [SartoxSoftware/audacium#42]
**Describe the bug**
In Audacium, if you try to import ffmpeg, nothing will happen. Even if you try to restart it and do it agian, it does not help.

**To Reproduce**
1. Open up preferences (Ctrl + P)
2. Click on libraries
3. Click on Locate...
4. Browse for avformat-55.dll
4. Click on OK
5. Nothing happens.

**Expected behavior**
ffmpeg is supposed to be added after you hit OK.

**Additional information**
 - OS: Windows 10
 - Audacium July 10th Build (the latest doesn't work.)

[this is my second issue that I've created on github. I hope it's understandable.]

**Comment by AnErrupTion** [comment]
@mystic-akito Could you try with the latest 1.0.0 release please?

**Comment by AnErrupTion** [comment]
Seems to be fixed with 1.0.0. Awaiting response.

**Comment by mystic-akito** [comment]
Sorry, I didn't go on github in a while, but yeah, it works now. Thank you for fixing.
![image](https://user-images.githubusercontent.com/50081890/146232006-cfc67160-ca29-4f12-ba1e-cea9e263f6be.png)

**Comment by dekrypted** [comment]
> Seems to be fixed with 1.0.0. Awaiting response.

It doesn't seem to be fixed for me. I'm on 1.0.0
