### ISSUE TITLE
Installer for macOS and Linux

### ISSUE THREAD

**Issue by NekomusuMae** [SartoxSoftware/audacium#43]
**Is your feature request related to a problem? Please describe.**
There is no installer for macOS and Linux. This is annoying as a Ubuntu user.

**Describe the solution you'd like**
Installer for macOS and Linux

**Describe alternatives you've considered**
Being able to `sudo apt install audacium` would be nice too.

**Comment by AnErrupTion** [comment]
To be able to install via apt, we would need to add the packages to the Ubuntu repositories, we're currently working on that. And for an installer, there is an AppImage for portable builds, though I understand having an installer would be nice.
We currectly do not have any installers. A solution would be to build a deb file for Ubuntu/Debian, we're thinking of doing that.

**Comment by ApoorvaKashyap** [comment]
I've created an unofficial deb file for the time being. It is available at [Debian/Ubuntu Package](https://github.com/ApoorvaKashyap/audacium/releases/tag/Audacium-Deb-July-22) . I you want you can use that for till an official release comes out.

**Comment by kajlamo** [comment]
.appimage, please.

**Comment by ApoorvaKashyap** [comment]
The AppImage file is available here : (https://github.com/SartoxOnlyGNU/audacium/actions/runs/1152257018). You need to download the zip file which has the title Audacium _Linux_...

**Comment by AnErrupTion** [comment]
Related to #28, closing...
