### ISSUE TITLE
Logo / style proposal for Audacium

### ISSUE THREAD

**Issue by bascurtiz** [SartoxSoftware/audacium#47]
![Audacium-banner-v1](https://user-images.githubusercontent.com/34075088/128556898-e6cfc03a-c481-4ac9-b8e8-528c61f0e557.png)
![Audacium-banner-v1-inverted](https://user-images.githubusercontent.com/34075088/128556907-8cb6a1a8-d4e9-461a-9f84-3759085583dd.png)

![Audacium-logo-v1](https://user-images.githubusercontent.com/34075088/128556920-4f7aec2e-5fc4-4b62-b533-18b0e6ddf769.png) ![Audacium-logo-v1-inverted](https://user-images.githubusercontent.com/34075088/128556930-d061a462-7c5e-476a-8567-345bbc808484.png)

![Audacium-icon-v1](https://user-images.githubusercontent.com/34075088/128556941-8f9cb0b3-79f4-4516-aca5-e74055e1f0d3.png) ![Audacium-icon-v1-inverted](https://user-images.githubusercontent.com/34075088/128556946-3aa1159f-5651-49ac-b5ea-595f0e5f38b3.png)

Why this logo / style instead of the [current one](https://user-images.githubusercontent.com/49339966/124761631-468df780-df32-11eb-84a6-5d17a9717fc2.png) ?

- **Shape**: Modern minimalism style (incl. reference to audio waveforms, left/right)

- **Colors**: Tasteful & multiple (reference to the spectrum of different frequencies, versatility of app features, without looking like a xmas fair)

- **Usability**: Can be used inverted (logo on dark bg, or bight bg)

- **Visually matching name:** Audacium.

"um" means neuter in Latin. It sounds like universum. Or auditorium. It has the feeling of being pretentious.
Now in its current state, it's Audacity... without telemetry.

The 3 key core goals listed are:

1. Restoring Audacity to what it was before, with no crash reporting (GH Issues exist for that), or very simple update checking (only at startup, not periodically)
2. Adding new features people want, listening closely to the community
3. Make the code base easier to work with, less confusing for a newbie

1st goal mentioned is how this all ofcourse started.
2nd goal is inspiring - and that should be visualized. Might attract new contributors.
3rd goal should somehow be represented visually too. Minimalism.

I tried to do so for all goals with my proposal.
Let me know if you all want this, so I will provide a package with color codes, png/svg, etc.

**NOTE:**
I made a Adobe Audition theme look-a-like for Audacity recently, see here: 
https://www.reddit.com/r/audacity/comments/owq5zl/audition_dark_theme_for_audacity/

I'm thinking of making a new default skin for Audacium too.
Keeping the colors used in the logo in check.

Then create a few different variants, so people can choose which color they want their waveform to be like:
- Orange
- Pink
- Purple
- Blue
- Turqoise

**Comment by AnErrupTion** [comment]
Looks stunning, however I think if we want color variants we would want to modify the audio waveforms and the A in the middle to a uniform color, and keep this current logo as the "universal" one.

**Comment by bascurtiz** [comment]
Good thinking! I'll play around with that idea.

**Comment by bascurtiz** [comment]
On 2nd thought, the A doesn't have to shift in color to make it work.
Since I use the colors of the logo in the audio waveforms.
Then we can use the Theme selector, to go with Dark Orange, Dark Pink, Dark Purple, Dark Blue, Dark Green.
I haven't created the `ImageCache.png` for the Bright/inverted variant yet, but first I'd like your opinion on these for Dark theme.

![Orange](https://user-images.githubusercontent.com/34075088/128580298-f8311f1b-09b0-4a9c-a5d5-363527445850.png)

![Pink](https://user-images.githubusercontent.com/34075088/128580309-b340132b-0a8c-4328-8433-85db5a8eaafe.png)

![Purple](https://user-images.githubusercontent.com/34075088/128580313-18b57176-e232-4d3c-b143-563dd0822a48.png)

![Blue](https://user-images.githubusercontent.com/34075088/128580319-72316142-ed23-4344-91f7-ba061877b472.png)

![Green](https://user-images.githubusercontent.com/34075088/128580321-d65d3ec3-7142-42bc-9f3c-12c0b218b2bd.png)

**Comment by ApoorvaKashyap** [comment]
Wow!!! This is pretty awesome.

**Comment by bascurtiz** [comment]
EDIT:
- Refined app icons added
- Audio waveforms cooler, so they don't get too vibrant + slightly lighter for better contrast

![Orange](https://user-images.githubusercontent.com/34075088/128601037-13205cce-abf8-49cf-8479-b1930887d3f0.png)

![Pink](https://user-images.githubusercontent.com/34075088/128601041-7f1bdc85-8e08-4a2d-85b5-05dfbc2d8513.png)

![Purple](https://user-images.githubusercontent.com/34075088/128601044-72c6efbd-85e9-4470-8116-4cd0c897925d.png)

![Blue](https://user-images.githubusercontent.com/34075088/128601045-81cfc220-e145-4674-94b6-9ca34c11350d.png)

![Green](https://user-images.githubusercontent.com/34075088/128601046-64f13bb6-8099-46ff-8158-47bb85ca3218.png)

**Comment by bascurtiz** [comment]
Bright themes:

![Orange-Bright-Theme-Example](https://user-images.githubusercontent.com/34075088/128606745-5f78c396-9d92-4fdf-96b2-b5cd549c8bcd.png)

![Pink-Bright-Theme-Example](https://user-images.githubusercontent.com/34075088/128606750-1705eda0-742b-4765-bdee-81852add6caa.png)

![Purple-Bright-Theme-Example](https://user-images.githubusercontent.com/34075088/128606754-910fe56c-27af-4107-be0d-b3c7fd8a3759.png)

![Blue-Bright-Theme-Example](https://user-images.githubusercontent.com/34075088/128606756-29aa379d-5fb1-426f-9cf1-bbd69e97f28c.png)

![Green-Bright-Theme-Example](https://user-images.githubusercontent.com/34075088/128606759-a59c7754-6526-4781-88e3-34db923aa99e.png)

**Comment by bascurtiz** [comment]
About Dark & Bright theme incl. icon & logo:

![About-Darkt](https://user-images.githubusercontent.com/34075088/128607207-6d8aa25b-861f-4622-9686-54c43ac521aa.png)

![About-Bright](https://user-images.githubusercontent.com/34075088/128607210-8a982747-a1fd-4cef-8e6a-1e589990a0d4.png)

**Comment by bascurtiz** [comment]
Icon Dark & Bright background:

![Audacium-icon-v1---dark-bg-256px](https://user-images.githubusercontent.com/34075088/128607939-19908854-923a-4447-b134-40632d233510.png) ![Audacium-icon-v1---bright-bg-256px](https://user-images.githubusercontent.com/34075088/128607936-85290c68-6ebf-41ac-acdd-277cbe36e03b.png)

**Comment by bascurtiz** [comment]
Original icons vs new:

![original-icon-vs-new](https://user-images.githubusercontent.com/34075088/128608300-cf02ab1c-5fb7-4d96-b0ce-ab6fb2f6786e.png)

**Comment by MissLav** [comment]
good work mate looks amazing

**Comment by realseb1g** [comment]
Man, I love this! Good job

**Comment by bascurtiz** [comment]
@AnErrupTion 
Can you confirm, I can push changes to the repo incl. altering `AllThemeResources.h` ?

**Comment by AnErrupTion** [comment]
@bascurtiz Sorry for the late response, those themes look great! You can do a pull request anytime soon :D

**Comment by bascurtiz** [comment]
Great! Will do tomorrow.

**Comment by jt15s** [comment]
Wow, this looks amazing! Have the icons and the graphics in the Installer been updated too? Might be good to update those as well if not.

**Comment by jt15s** [comment]
BTW when can one expect a release with the updated branding?

**Comment by AnErrupTion** [comment]
@bascurtiz Is it all done or are there some missing pieces here and there?

**Comment by bascurtiz** [comment]
All done

**Comment by AnErrupTion** [comment]
Alright! Closing.
