### ISSUE TITLE
10 million samples limit

### ISSUE THREAD

**Issue by xtemp09** [SartoxSoftware/audacium#49]
Could you remove 10 million samples limit in [src/FreqWindow.cpp](https://github.com/SartoxOnlyGNU/audacium/blob/master/src/FreqWindow.cpp#L596)?

I would be really grateful if you will increase the limit.

**Comment by AnErrupTion** [comment]
This might make Audacium lag or this might even create bugs. Why would you create 10 million samples in the first place? (Not to judge, just curious)

**Comment by xtemp09** [comment]
https://user-images.githubusercontent.com/9303235/129841257-34e6b925-ce82-4225-bd64-3d1a5cb8e08c.png

**Comment by AnErrupTion** [comment]
@xtemp09 Could you give me that track or a similarly long track and how you were able to reproduce that? I would appreciate that.

**Comment by xtemp09** [comment]
https://cloud.mail.ru/public/4AYT/1suMCGFBD

Select the track, choose Analyze->Plot Spectrum

**Comment by AnErrupTion** [comment]
What I suggested was true, removing that limit makes Audacium lag. It works though.
