### ISSUE TITLE
Installer Markdown/HTML does not render properly

### ISSUE THREAD

**Issue by jt15s** [SartoxSoftware/audacium#51]
When installing Audacium, the information panel that pops up after Audacium has been installed does not render the mix of HTML and Markdown properly, and instead the user is presented with the plain text plus formatting marks:
![image](https://user-images.githubusercontent.com/75475674/132090353-cd163229-e051-450e-8220-98a3aec40967.png)

Thanks in advance!

**Comment by liamreoch** [comment]
What OS?

**Comment by jt15s** [comment]
@liamreoch Windows 11.

**Comment by AnErrupTion** [comment]
This is probably going to be replaced by simple text. (I don't think we can render HTML here)

**Comment by AnErrupTion** [comment]
Fixed in recent commit, closing.
