### ISSUE TITLE
Typo in Wiki: Building for macOS running on Apple Silicon

### ISSUE THREAD

**Issue by jacop5** [SartoxSoftware/audacium#87]
Since the correct generator name for Apple XCode is "Xcode", `cmake` won't run unless it is written with the right capitalisation. And also, no directory exists under `audacium/audacium`, so the source directory should be `..` 
In the end, we should have:

`$ cmake -G Xcode -T buildsystem=1 -Daudacity_use_mad=off -Daudacity_use_id3tag=off ..`

Instead of:

`$ cmake -GXCode -T buildsystem=1 -Daudacity_use_mad=off -Daudacity_use_id3tag=off ../audacium`

**Comment by AnErrupTion** [comment]
> also, no directory exists under audacium/audacium, so the source directory should be ..
Well, about that, if it's just "..", it will not work, it has to be "../audacium" (at least on Linux)

**Comment by jacop5** [comment]
<img width="889" alt="Schermata 2021-12-29 alle 18 11 44" src="https://user-images.githubusercontent.com/96621577/147686920-4b7d427e-6d36-4e97-ba97-d73ecca32265.png">
If I use `../audacium` it doesn't work, while if I use `..` it does.

**Comment by AnErrupTion** [comment]
Well, sorry for the long wait, but I've gone ahead and corrected the changes in the wiki.
